# Site settings
title: kodekodein
description: Let's Code
baseurl: '' # for test: remove string '/space-jekyll-template' to ''
url: '' # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Rez
user_title: Rez - Learner
email: moehamadrezha@gmail.com
twitter_username: r18526
github_username:  rezafurnama
gplus_username:  foo
linkedin_public_url: rezafurnama # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: foo
profile_picture: https://68.media.tumblr.com/93f384858e9273d5b980b418e2f2f4d5/tumblr_o5i2aybLJG1uapsfmo2_250.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: Home
      url: /
      key_trigger: 1
    - title: Posts
      url: /posts
      key_trigger: 2
    - title: Tags
      url: /tags
      key_trigger: 3
    - title: About
      url: /about
      key_trigger: 4
  section_2:
    - title: My Github
      url: http://www.github.com/rezafurnama
      new_tab: true
      key_trigger: g
    - title: Twitter
      url: http://www.twitter.com/rez18526
      new_tab: true
      key_trigger: t
    - title: Search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: Simple PHP MVC
    url: https://github.com/RezaFurnama/phpmvc
  - name: Kodekodein.me
    url: https://github.com/RezaFurnama/rezafurnama.github.io
  - name: Simple DiscordBot
    url: https://github.com/RezaFurnama/Mukidi-DiscordBot

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
